name: reading_journal

description: Reading Journal multiplataforma basado en los requisitos proporcionados.
publish_to: 'none'
version: 0.4.1+5

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  file_picker: ^13.1.0
  intl: ^0.20.3
  share_plus: ^13.3.0
  uuid: ^4.6.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/readbloom_logo.png
    - assets/themes/

flutter_launcher_icons:
  android: true
  windows:
    generate: true
    image_path: assets/readbloom_logo.png
    icon_size: 48
  image_path: assets/readbloom_logo.png
  min_sdk_android: 21

